This file contains basic use-methods of NumPy module I summarized from courses and some online sources.

[python numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/#numpy)

# NumPy
NumPy is the core library for scientific computing in Python.

NumPy’s main object is the homogeneous multidimensional **array**. It is a table of elements, all of the same type, indexed by a tuple of nonnegative integers. In NumPy dimensions are called axes.

## 1. Array initialization

In [56]:
import numpy as np

# create by myself
vector = np.array([10, 20, 30], int)
print('vector\n', vector)
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]],int)
print('\nmatrix\n', matrix)

# create certain type array
zeros = np.zeros((2, 2))
print('\nzeros\n', zeros)
ones = np.ones((1, 2))
print('\nones\n', ones)
full = np.full((2, 2), 7)
print('\nfull\n', full)
eye = np.eye(2)
print('\neye\n', eye)
random = np.random.random((2, 2))
print('\nrandom\n', random)

# create from other sources
#array = np.genfromtxt('file_name.csv', dtype = 'U75', skip_header = 1, delimiter = ',')

vector
 [10 20 30]

matrix
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

zeros
 [[ 0.  0.]
 [ 0.  0.]]

ones
 [[ 1.  1.]]

full
 [[7 7]
 [7 7]]

eye
 [[ 1.  0.]
 [ 0.  1.]]

random
 [[ 0.33788885  0.08855071]
 [ 0.51118744  0.90291024]]


## 2. Useful attributes for array object

In [52]:
# the shape of the array
vector_shape = vector.shape
print('vector_shape\n', vector_shape)
matrix_shape = matrix.shape
print('\nmatrix_shape\n', matrix_shape)

# the data type of the array
data_type = vector.dtype
print('\ndata_type\n', data_type)

# change the date type of the array
float_vector = vector.astype(float)
print('\nfloat_vector\n', float_vector)

# the sum of the array
# same: sum(), mean(), max(), std()
vector_sum = vector.sum()
print('\nvector_sum\n', vector_sum)
matrix_sum = matrix.sum(axis=1)  # sum on each row
print('\nmatrix_sum\n', matrix_sum)

vector_shape
 (3,)

matrix_shape
 (3, 3)

data_type
 int64

float_vector
 [ 10.  20.  30.]

vector_sum
 60

matrix_sum
 [10 45 75]


## 3. Array indexing and slicing

In [46]:
# vector
print('vector\n')
print(vector[0])
print(vector[:2])

# matrix
print('\nmatrix\n')
print(matrix[0])
print(matrix[:2])
print(matrix[0, 1])
print(matrix[:2, :2])
print(matrix[:2, :])

# use boolean
print('\nuse boolean\n')
print(vector[vector > 10])
print(matrix[matrix > 10])
print(matrix[matrix[:, 1] > 10])
print(matrix[matrix[:, 1] > 10, :2])
print(matrix[(matrix[:, 0] == 5) & (matrix[:, 1] == 10)])
print(matrix[(matrix[:, 0] == 5) | (matrix[:, 1] == 25)])

# array replace
print('\narray replace\n')
matrix_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_1[:, 2] = 0
print(matrix_1)

vector

10
[10 20]

matrix

[ 0 10  0]
[[ 0 10  0]
 [20 25  0]]
10
[[ 0 10]
 [20 25]]
[[ 0 10  0]
 [20 25  0]]

use boolean

[20 30]
[20 25 35 40]
[[20 25  0]
 [35 40  0]]
[[20 25]
 [35 40]]
[]
[[20 25  0]]

array replace

[[1 2 0]
 [4 5 0]
 [7 8 0]]


## 4. Array math

In [51]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# elementwise sum
print('sum\n')
print(x + y)
#print(np.add(x, y))

# elementwise difference
print('\ndifference\n')
print(x - y)
#print(np.subtract(x, y))

# elementwise product
print('\nproduct\n')
print(x * y)
#print(np.multiply(x, y))

# elementwise division
print('\ndivision\n')
print(x / y)
#print(np.divide(x, y))

# elementwise square root
print('\nsquare root\n')
print(np.sqrt(x))


# inner product of vectors
print('\ninner product of vectors\n')
# print(v.dot(w))
print(np.dot(v, w))

# matrix vector product
print('\nmatrix vector product\n')
# print(x.dot(v))
print(np.dot(x, v))

# matrix matrix product
print('\nmatrix matrix product\n')
# print(x.dot(y))
print(np.dot(x, y))

sum

[[ 6  8]
 [10 12]]

difference

[[-4 -4]
 [-4 -4]]

product

[[ 5 12]
 [21 32]]

division

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]

square root

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]

inner product of vectors

219

matrix vector product

[29 67]

matrix matrix product

[[19 22]
 [43 50]]
